### ISSUE TITLE
Chroma kss markup is causing an Error with scss-lint

### ISSUE THREAD

**Issue by sarahjean** [JohnAlbin/chroma#13]
Trying out a zen 7.6 subtheme, so I wasn't sure whether to report this here or over there, but scss-lint/gulp-scss-lint seems to be choking on these lines:
```
// scss-lint:disable Comment
/*
#{chroma-kss-markup()}
*/
```

I had to run the gulp task in verbose mode and then run that output straight on the command line to track it down, the gulp error was 'internal software error'. This is the error i am seeing:

`SCSSLint::Linter::SpaceBetweenParens raised unexpected error linting file /path//to/sass/style-guide/chroma-kss-markup.scss: 'undefined method `count' for nil:NilClass'`

**Comment by JohnAlbin** [comment]
Yep, I was seeing the same thing on Friday. It's a bug in sass-lint. https://github.com/brigade/scss-lint/issues/568

**Comment by JohnAlbin** [comment]
@sarahjean If you add these lines to the end of your .scss-lint.yml file, it should work-around the bug in scss-lint.

```
  # scss-lint 0.41.0 dies parsing chroma-kss-markup.scss when using SpaceBetweenParens
  # See https://github.com/brigade/scss-lint/issues/568
  SpaceBetweenParens:
    enabled: false
```

**Comment by sarahjean** [comment]
It did indeed, thanks!

**Comment by JohnAlbin** [comment]
Cool!

I'll keep this ticket open to track the scss-lint bug and close it out when the bug is fixed.

**Comment by JohnAlbin** [comment]
Upstream issue is fixed. Need to confirm the work-around is no longer needed.

**Comment by JohnAlbin** [comment]
The work-around is no longer needed.
