### ISSUE TITLE
Register on bower

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/chroma#14]
So I went to register Chroma on Bower now that it has a 1.0.0 release, but I got this:

```
$ bower register chroma git@github.com:JohnAlbin/chroma.git
? May bower anonymously report usage statistics to improve the tool over time? Yes
bower                          convert Converted git@github.com:JohnAlbin/chroma.git to git://github.com/JohnAlbin/chroma.git
bower chroma#*                 resolve git://github.com/JohnAlbin/chroma.git#*
bower chroma#*                download https://github.com/JohnAlbin/chroma/archive/1.0.0.tar.gz
bower chroma#*                 extract archive.tar.gz
bower chroma#*                resolved git://github.com/JohnAlbin/chroma.git#1.0.0
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower chroma                  register git://github.com/JohnAlbin/chroma.git
bower                       EDUPLICATE Duplicate package
```

It looks like @crazyrohila registered his old fork of Chroma on Bower 5 months ago. Sanjay, can you help me get the original Chroma URL registered in the Bower registry?

According to the [Bower registry homepage](https://github.com/bower/registry#unregister-package), you can unregister your version of Chroma and I can then add it back with the proper URL. Just follow these steps:

```
bower login
# enter GitHub username and password
? Username:
? Password:
# unregister packages after successful login
bower unregister chroma
```

**Comment by crazyrohila** [comment]
I will unregister now. BTW I can't recall any register to bower. It's weird. :/

**Comment by crazyrohila** [comment]
Done.

**Comment by JohnAlbin** [comment]
@crazyrohila Woo-hoo! You rock, Sanjay. Thanks for you help!

I've registered Chroma with Bower and confirmed that I can find it in the registry and can install it via `bower install chroma --save-dev`.
