### ISSUE TITLE
Dependency for kss-node doesn't fix any version

### ISSUE THREAD

**Issue by rodrigoaguilera** [JohnAlbin/chroma#19]
I think the package.json should fix the compatible version for kss-node.

Something changed in kss-node that is breaking libsass for us and since it downloads the latest version everytime we do "npm install" the automated build broke without changing anything related to the theme.

**Comment by JohnAlbin** [comment]
kss is a dev dependency of chroma-sass. Meaning it does not get installed when you do a `npm install chroma-sass`. None of the `devDependencies` get installed when you install a node.js package. Only the `dependencies` get installed and chroma-sass has none.


Go into an empty directory and try, you'll see it only creates chroma-sass inside node_modules.
